export enum PermissionKey {
  ChatRead = 'chat:read',
  ChatWrite = 'chat:write',
  ChatAssign = 'chat:assign',
  ChatDelete = 'chat:delete',
  ChannelRead = 'channel:read',
  ChannelManage = 'channel:manage',
  ContactRead = 'contact:read',
  ContactManage = 'contact:manage',
  AutomationRead = 'automation:read',
  AutomationManage = 'automation:manage',
  SettingsRead = 'settings:read',
  SettingsManage = 'settings:manage',
  UserRead = 'user:read',
  UserManage = 'user:manage',
  RoleRead = 'role:read',
  RoleManage = 'role:manage',
}
